spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bdjosefita
    username: postgres
    password: Ol4kases
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# Ruta donde se guardarán las fotos de las prendas
# Windows: app.imagenes.ruta: C:/josefita/imagenes
# Linux/Mac: app.imagenes.ruta: /var/josefita/imagenes
app:
  imagenes:
    ruta: ./imagenes
