spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/bdjosefita}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:Ol4kases}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# En local usa ./imagenes (carpeta al lado del JAR)
# En Render/Docker usa /app/imagenes (creada en el Dockerfile)
app:
  imagenes:
    ruta: ${IMAGENES_RUTA:./imagenes}
